server:
  port: 8333
  
app:
  loadUser: true
  ordercount: 10

debug: false

spring:
  application:
    name: order-microservice

  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:testdb